apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    stage: local
    app: dev
spec:
  storageClassName: sc-db
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi