apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-1
  labels:
    stage: local
    type: local
spec:
  storageClassName: sc-db
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/var/lib/mysql"
  persistentVolumeReclaimPolicy: Recycle